BUG: Update "pre-commit" workflow to support reuse from private project
Follow-up of bf50210585 ("COMP: Support reuse of "commit-message" GitHub
workflow", 2024-08-19)

This ensures the "gsactions/commit-message-checker" internally using GraphQL
along with the equivalent of the "Get a Pull Request" REST endpoint is granted
with the expected permissions:
* "Pull requests" repository permissions (read)
* "Contents" repository permissions (read)

While testing the workflow, the following error was encountered,
indicating a permissions issue:

> Run gsactions/commit-message-checker@16fa2d5de096ae0d35626443bcd24f1e756cafee
> Error: GraphqlResponseError: Request failed due to following response errors:
> - Resource not accessible by integration

To address this, repository permissions were adjusted to ensure that the action
can properly access the necessary resources.



For reference, see the "Get a Pull Request" API documentation:
https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request