COMP: Fix qMRMLMarkupsROIWidget build error against Qt 5.10
This commit removes uses of "PlaceholderText" in UI file that was
originally introduced in 294e142189 (ENH: Refactor markups module widgets)

It fixes the following error:

  error: ‘PlaceholderText’ is not a member of ‘QPalette’

QPalette::PlaceholderText was introduced in Qt 5.12.
See https://github.com/qt/qtbase/commit/ebd3a13b807c6af2684b42d3912549caf7ef82aa