BUG: Fix traceback setting unitAwareProperties
The unitAwareProperties property returns a type that doesn't support the in-place bitwise AND operator &=.

This fixes:

TypeError: unsupported operand type(s) for &=: 'UnitAwareProperty>' and 'int'