COMP: Fix Markups build error ensuring SH headers are available
This commit fixes a build error caused by a change in the build order
of the loadable module and introduced by r25551 (ENH: Allow display
transform glyphs at markup positions).

Before r25551:

[...]
Colors
SubjectHierarchy
Transforms
Annotations
Data
DoubleArrays
Markups
[...]


After r25551:

[...]
Colors
Annotations
Markups
Transforms
SubjectHierarchy
Data
DoubleArrays
[...]

Build error fixed by this commit:

/path/to/Slicer/Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx:28:50: fatal error: qSlicerSubjectHierarchyPluginHandler.h: No such file or directory
compilation terminated.

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25559
git-svn-id: http://svn.slicer.org/Slicer4/trunk@25559 3bd1e089-480b-0410-8dfb-8563597acbee