COMP: Update qRestAPI to fix windows link error
This commit fixes the following link error introduced
by 69f8d8505 (STYLE: Simplify ExtensionsManagerModelTest removing duplicated function)

Link error:

    error LNK2019: unresolved external symbol "__declspec(dllimport) public:
    static class QMap<class QString,class QVariant> __cdecl
    qRestAPI::qVariantMapFlattened(class QMap<class QString,class QVariant> const &)" (...)
    referenced in function "private: static class QMap<class QString,class QVariant>
    __cdecl qSlicerExtensionsManagerModelTester::extensionMetadata(class QString const &,int,bool,bool)" (...)


List of changes:

$ git shortlog 98c858c..ea5e85a --no-merges
Jean-Christophe Fillion-Robin (5):
      cmake: Update minimum required version to 3.5.0
      cmake: Re-organize code
      cmake: Simplify code by automatically including current directories
      Update README and add CONTRIBUTING guidelines
      COMP: Fix export header to support linking of static qRestAPI