COMP: Fix promoted widget headers in qSlicerTractographyDisplayWidget.ui
Promoted headers are now specified using the proper case. For
example: "ctkcollapsiblegroupBox.h" instead of "ctkCollapsibleGroupBox.h"

This will fix the following compilation issue on case sensitive file system:

In file included from /home/jchris/Projects/Slicer4/Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayWidget.cxx:5:
/path/to/Modules/Loadable/TractographyDisplay/Widgets/ui_qSlicerTractographyDisplayWidget.h:27:36: error: ctkcollapsiblegroupbox.h: No such file or directory
/path/to/Modules/Loadable/TractographyDisplay/Widgets/ui_qSlicerTractographyDisplayWidget.h:28:39: error: ctkmaterialpropertywidget.h: No such file or directory

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=20541
git-svn-id: http://svn.slicer.org/Slicer4/trunk@20541 3bd1e089-480b-0410-8dfb-8563597acbee