COMP: Consistently use vtkMath::Pi() instead of M_PI defines
Address the following Windows build error:

  C:\path\to\Slicer\Libs\MRML\DisplayableManager\vtkMRMLSliceIntersectionRepresentation2D.cxx(548,34):
  error C2065: 'M_PI_2': undeclared identifier [...]

Rather than adding the missing "math.h" include, this commit promotes
consistency within the codebase by using "vtkMath::Pi()"