COMP: Add MSVC compatibility check when using Qt 5
Slicer with Qt 5.15.2 does not build successfully when using MSVC 1451 (Visual Studio 2026 18.6) due to stdext no longer being available.

49>C:\Qt\5.15.2\msvc2019_64\include\QtCore\qlist.h(915,29): error C2653: 'stdext': is not a class or namespace name [C:\S5R\CTK-build\PythonQtGenerator-build\PythonQtGenerator.vcxproj] [C:\S5R\CTK-build\PythonQtGenerator.vcxproj]

A guard was added for older MSVC versions for Qt 5.15 branch in https://github.com/qt/qtbase/commit/165daa88c1e5a768cce18c10bf570fe22a741411.

The guard was added for Qt6 in
https://github.com/qt/qtbase/commit/52b6258ec846cc53ebdb1c8167edd30db39c7891 which started with Qt 6.7 and backported to some older branches. Slicer currently requires Qt 6.8 or newer so we don't need checks for older Qt 6 versions.