COMP: Update to ITK and SimpleITK to include fix for itkStaticConstMacro.
This is an attempt to address SimpleITK build error on MacOSX El Capitan
similar to the the following one:

//------------
In file included from /path/to/ITKv4/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_c_vector.h:26:
/path/to/ITKv4/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_numeric_traits.h:388:41: error: declaration of constexpr static data member 'zero' requires an initializer
  static VNL_EXPORT VCL_CONSTEXPR float zero VCL_STATIC_CONST_INIT_FLOAT_DECL(0.0F);
//------------

More details here: http://slicer-devel.65872.n3.nabble.com/El-Capitan-SimpleITK-build-errors-td4036108.html

Reported-by: Christian Herz <christian.herz@mevis.fraunhofer.de>



List of associated ITK changes:

$ git shortlog 615607f..b61e91d --no-merges
Dzenan Zukic (1):
      COMP: fix itkStaticAssert warnings with clang++

Hans Johnson (1):
      COMP: Incomplete solution for operators corrected

Jean-Christophe Fillion-Robin (1):
      COMP: Fix Slicer MacOSX extension packaging setting CMP0042 policy to OLD

Jon Haitz Legarreta (1):
      BUG: Fix OpenCVBridge bug for two-byte images.

Lucas Gandel (2):
      BUG: Change CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR
      BUG: Fix multiple external modules wrapping

Martin Michlmayr (1):
      COMP: fixed error "Dunno about this gcc" for gcc 6

Matthew McCormick (12):
      DOC: Update WikiExamples to 2016-10-20
      BUG: BUILD_TESTING should be not advanced.
      COMP: Use enum in itkStaticConstMacro for old GCC.
      BUG: Correct FlatStructuringElement wrapping location.
      BUG: Correct itkStaticConstMacro GCC version comparison operator.
      BUG: Improve GCC detection in itkStaticAssert.h preprocessor macro.
      BUG: Fix OpenCV version check.
      DOC: Update the SphinxExamples Remote Module.
      COMP: Wrap FlatStructuringElement before other classes.
      COMP: Workaround inconsistent OpenCV pre-processor variables.
      COMP: Update CastXML to support wrapping with GCC 6.
      ENH: Allow ITKVideoBridgeOpenCV to be built externally.

Sumedha Singla (3):
      ENH: Fixed the numeric traits for datatypes
      DOC: Added a comment to support the changes in numeric traits datatypes.
      BUG: Invalid memory access of itk::NotAlmostEquals Bug#ITK-3403



List of SimpleITK changes:

$ git shortlog 6f184b4..ee2a30c --no-merges
Bradley Lowekamp (39):
      Adding wrapping for FFT PadImageFilter
      Fix CSharp and Java boundary condition enum for test
Bradley Lowekamp (39):
      Adding wrapping for FFT PadImageFilter
      Fix CSharp and Java boundary condition enum for test
      Correcting Java and CSharp enum types
      Updating ITK Superbuild towards 4.9 along master branch
      Adding print of learning rate in OptimizerScales test
      Adding initial json file to generate filter
      Replacing json with generated source files.
      Adding manual changes to the LandmarkBasedTransformInitializer
      Expanding testing for the LandmarkBasedTransformInitializer
      Updating ITK Superbuild version
      BUG: Update ITK_DIR to match version
      Moving Python Wrapping to sub-directory
      Moving Ruby wrapping to sub-directory
      Moving Tcl and Lua wrapping for sub-directories
      Move CSharp wrapping to sub-directory
      Moving Java wrapping to separate directory
      Move R wrapping to sub-directory
      Adding SimpleITK.i to each language
      Adding script using to build anaconda distributions
      Update to new CMake policies to reduce warnings
      Add comments and working directories to Py VirtualEnv script
      Correct path for Java packaging for the dist target.
      Increase tolerance for MaskedFFTNormazliedCorrelationImageFilter
      Update ITK Superbuild version to 4.9rc3
      Updated SWIG superbuild version to 3.0.9
      Updating ImageCompare to find alternate baseline images.
      Adding alternative baseline images for ITK 4.9 changes to the algorithim
      Adding new baselines for deconvolution with FFTW
      Adding R Example for filter callbacks
      Adding documentation for R lambda callback usage
      Update tolerance for AdaptiveHistogramEqualizationImageFilter test
      Updating ITK Superbuild version along release branch
      BUG: Address HistogramMatching error with number of bins
      Updating ITK along release branch
      Disable Explicit ITK instantiation for gcc 4.1
      Adding needed quote to CMake variable to handle null strings.
      Updating to latest hash on ITK release branch for 4.9
      Revert "Disable Explicit ITK instantiation for gcc 4.1"
      BUG: Fix conversion to int in overloaded > and >= operators

David T. Chen (3):
      Added SITK_OVERRIDE macro
      Changed SITK_OVERRIDE to ITK_OVERRIDE
      Fix for CMake CMP0064 warning

Richard Beare (3):
      Use ExternalData for R data
      Use member function syntax to call member functions
      Support for using an R function as a callback.

Ziv Yaniv (3):
      BUG: Fixed bug converting between vector and set of ITK points.
      BUG: Fixed crash when reference image is not set for BSpline initialization.
      COMP: fixed failed wrapping due to method signature differences

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24911
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24911 3bd1e089-480b-0410-8dfb-8563597acbee