COMP: Fix missing "itkFactoryRegistrationConfigure.h" build error
This will fix build errors of the form:

../ITKFactoryRegistration/itkFactoryRegistration.h:6:45: error: itkFactoryRegistrationConfigure.h: No such file or directory
../Libs/MRML/Logic/Testing/Cxx/vtkMRMLSliceLogicTest2.cxx:49:
../Libs/ITKFactoryRegistration/itkFactoryRegistration.h:10: error: expected constructor, destructor, or type conversion before 'void'
../Libs/MRML/Logic/Testing/Cxx/vtkMRMLSliceLogicTest2.cxx: In function 'int vtkMRMLSliceLogicTest2(int, char**)':
../Libs/MRML/Logic/Testing/Cxx/vtkMRMLSliceLogicTest2.cxx:56: error: 'itkFactoryRegistration' is not a member of 'itk'


Follow-up of commit r21723

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=21725
git-svn-id: http://svn.slicer.org/Slicer4/trunk@21725 3bd1e089-480b-0410-8dfb-8563597acbee