BUG: Fix AttributeError in SliceViewAnnotations.updateViewAnnotations()
This commit fixes a regression introduced in r24238 (BUG: Fix
SliceViewAnnotations AttributeError happening on closing Slicer) where
the ivar sliceViewNames (of type 'list') is directly set with the
value returned by app.layoutManager().sliceViewNames() (of type 'tuple').

Considering that tuple are immutable and list mutable, this explained the
error in the function "updateViewAnnotations":

  AttributeError: 'tuple' object has no attribute 'append'

By converting the returned tuple to a list, it fixes the issue.

Reviewed-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24684
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24684 3bd1e089-480b-0410-8dfb-8563597acbee