COMP: Update python to fix numpy build issue on windows
This commit fixes the following error:

  ModuleNotFoundError: No module named '_distutils_findvs'

List of changes:

$ git shortlog b27121b..610e8256 --no-merges
Jean-Christophe Fillion-Robin (1):
      Add support for building _distutils_findvs module introduced in Python 3.6

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28127
git-svn-id: http://svn.slicer.org/Slicer4/trunk@28127 3bd1e089-480b-0410-8dfb-8563597acbee