COMP: C++11 convertsion of types
error: no viable conversion from 'DiffusionTensor3DExtended<float>' to 'DiffusionTensor3DExtended<double>'

By preferring initialization to assignment this error is avoided.

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=22915
git-svn-id: http://svn.slicer.org/Slicer4/trunk@22915 3bd1e089-480b-0410-8dfb-8563597acbee