COMP: Fix DCMTK build error llvm-gcc-4.2 on MacOSX.
Updated version of DCMTK includes this commit:

//--------------
commit commontk/DCMTK@545de87
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date:   Mon Oct 5 21:06:36 2015 -0400

    Fix dcmsr build error on llvm-gcc-4.2 on MacOSX.

    While maintaining the fix introduced in the previous commit, this commit
    also fixes the following error:

    Linking CXX shared library ../../lib/libdcmsr.dylib
    ld: duplicate symbol DSRTree<DSRDocumentTreeNode>::isEmpty() const  in
    CMakeFiles/dcmsr.dir/dsrdocst.cc.o and
    CMakeFiles/dcmsr.dir/dsrdoc.cc.o for architecture x86_64
    collect2: ld returned 1 exit status
    make[2]: *** [lib/libdcmsr.3.6.1.dylib] Error 1
    make[1]: *** [dcmsr/libsrc/CMakeFiles/dcmsr.dir/all] Error 2

    That was happening using the following compiler:
    i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc.
    build 5658) (LLVM build 2336.1.00)

    See http://slicer-devel.65872.n3.nabble.com/dcmtk-compile-regression-td4035162.html

    Reported-by: Bill Lorensen <bill.lorensen@gmail.com>
    Tested-by: Bill Lorensen <bill.lorensen@gmail.com>
//--------------

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24598
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24598 3bd1e089-480b-0410-8dfb-8563597acbee