COMP: Fix some compilation errors in Visual Studio 2013
Compiles in Debug configuration as long as EMSegment module, numpy and
OpenSSL support disabled.

Errors fixed by changes in vtkMRMLCoreTestingMacros are similar to the
following:

8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---
Error   2   error C2678: binary '<<' : no operator found which takes a left-hand operand of type 'std::basic_ostream<char,std::char_traits<char>>' (or there is no acceptable conversion)   C:\dev\Slicer\Libs\MRML\Core\Testing\vtkMRMLDiffusionTensorVolumeDisplayNodeTest1.cxx   24
Error   3   error C2088: '<<' : illegal for class   C:\dev\Slicer\Libs\MRML\Core\Testing\vtkMRMLDiffusionTensorVolumeDisplayNodeTest1.cxx   24
Error   4   error C2678: binary '<<' : no operator found which takes a left-hand operand of type 'std::basic_ostream<char,std::char_traits<char>>' (or there is no acceptable conversion)   C:\dev\Slicer\Libs\MRML\Core\Testing\vtkMRMLDiffusionWeightedVolumeDisplayNodeTest1.cxx 23
Error   5   error C2088: '<<' : illegal for class   C:\dev\Slicer\Libs\MRML\Core\Testing\vtkMRMLDiffusionWeightedVolumeDisplayNodeTest1.cxx 23
[...]
8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24477
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24477 3bd1e089-480b-0410-8dfb-8563597acbee