COMP: Build FiberTractMeasurements only if diffusion support is enabled
This commit fixes a build error ensuring that the module
FiberTractMeasurements first introduced in r23831 (ENH: Added first
implementation of FiberTractMeasurements CLI module) is build only
when needed.

Build error:

[...]
[ 34%] Built target vtkSlicerSubjectHierarchyModuleMRMLPythonD
/path/to/Slicer/Modules/CLI/FiberTractMeasurements/FiberTractMeasurements.cxx:23:36: fatal error: vtkMRMLFiberBundleNode.h: No such file or directory
 #include <vtkMRMLFiberBundleNode.h>
[...]

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23940
git-svn-id: http://svn.slicer.org/Slicer4/trunk@23940 3bd1e089-480b-0410-8dfb-8563597acbee