BUG: Fix support for generating sphinx doc from Slicer Python environment
This commit fixes the error reported below by ensuring the path to the
"slicer" package available in the source tree is prepended only if
not already available from the Slicer Python environment where modules
like MRMLCorePython have been successfully imported.

Note that since "slicer.kits" is only available in the Slicer Python environment,
its presence usually indicates that (1) the slicer module is available and
(2) the kits (mrml, vtkAddon, vtkSegmentationCore, ..) have been imported.

Error:

WARNING: autodoc: failed to import module 'parameterNodeWrapper' from module 'slicer'; the following exception was raised:
Traceback (most recent call last):
  [...]
  File "/path/to/Slicer/Base/Python/slicer/parameterNodeWrapper/__init__.py", line 5, in <module>
    from .guiConnectors import *
  File "/path/to/Slicer/Base/Python/slicer/parameterNodeWrapper/guiConnectors.py", line 16, in <module>
    from . import parameterPack as pack
  File "/path/to/Slicer/Base/Python/slicer/parameterNodeWrapper/parameterPack.py", line 10, in <module>
    from .serializers import (
  File "/path/to/Slicer/Base/Python/slicer/parameterNodeWrapper/serializers.py", line 402, in <module>
    class NodeSerializer(Serializer):
  File "/path/to/Slicer/Base/Python/slicer/parameterNodeWrapper/serializers.py", line 424, in NodeSerializer
    def write(self, parameterNode, name: str, value: slicer.vtkMRMLNode) -> None:
AttributeError: module 'slicer' has no attribute 'vtkMRMLNode'