COMP: Fix parallel build error adding missing PyPI dependency for python-dateutil
Fix the error reported below ensuring "python-dateutil" dependency "six"
is explicitly specified within its external project, ensuring it is not
installed as side effect of an unrelated external project.


```
$ cat /path/to/python-extension-manager-ssl-requirements-install-err.log

ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    six>=1.5 from https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from python-dateutil==2.8.2->-r /Users/svc-dashboard/D/P/A/python-extension-manager-ssl-requirements-requirements.txt (line 87))
WARNING: There was an error checking the latest version of pip.
```