COMP: Update loadable module factory to fix build with python disabled
This commit fixes a regression introduced in f8fc53b90 (BUG: Ensure scripted
module can depend on wrapped C++ classes from other modules).

It fixes the following error reported when building Slicer with the option
Slicer_USE_PYTHONQT set to OFF.

Build error:

In file included from /path/to/Slicer/Base/QTCore/qSlicerLoadableModuleFactory.cxx:40:
/path/to/Base/QTCore/qSlicerCorePythonManager.h:25:11: fatal error: ctkAbstractPythonManager.h: No such file or directory
   25 | # include <ctkAbstractPythonManager.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reported-by: Jon Haitz Legarreta Gorroño <jon.haitz.legarreta@gmail.com>