COMP: Fix build error re-adding missing conventionalQuantitativeView
This commit is a follow-up of 1959541 (COMP: Do not remove legacy chart
views yet)

If fixes the following error:

  /path/to/Slicer/Libs/MRML/Logic/vtkMRMLLayoutLogic.cxx:1557:42:
  error: ‘conventionalQuantitativeView’ was not declared in this scope
                                          conventionalQuantitativeView);
                                          ^