COMP: Fix install of "pyparsing" and "packaging" adding setuptools dependency
Following r27374 (ENH: Update pip from 10.0.1 to 18.0, and setuptools
from 39.2.0 to 40.2.0), pyparsing and packaging packages were removed
because they were vendorized in the new updated setuptools.

Then, they were re-introduced in r27279 (BUG: Ensure python-packaging is
available) because they were in fact directly used in script like
"DICOMWidgets.py" to parse version relying on "packaging.version".

This commit fixes regression introduced in r27279 by explicitly adding
setuptools as a dependency of "pyparsing" and "packaging".

It avoids error like the following:

```
cat /Volumes/Dashboards/Preview/Slicer-0-build/python-pyparsing-prefix/src/python-pyparsing-stamp/python-pyparsing-install-err.log
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27995
git-svn-id: http://svn.slicer.org/Slicer4/trunk@27995 3bd1e089-480b-0410-8dfb-8563597acbee