BUG: tpycl.py - use sys.platform instead of platform.system()
* On some system (i.e macosx 10.6.7 32bits, using platform.system()
is causing issue. See below:

>>> platform.system()

Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/path/to/Slicer.app/Contents/lib/Python/lib/python2.6/platform.py", line 1272, in system
return uname()[0]
File "/path/to/Slicer.app/Contents/lib/Python/lib/python2.6/platform.py", line 1239, in uname
processor = _syscmd_uname('-p','')
File "/path/to/Slicer.app/Contents/lib/Python/lib/python2.6/platform.py", line 995, in _syscmd_uname
output = string.strip(f.read())
IOError: [Errno 4] Interrupted system call

* By using 'sys.platform' it's clear we find a way around the issue
instead of solving the root problem.

* The following link could reveal useful into implementing a more
general solution:

 - http://code.activestate.com/lists/python-list/48683/
    => Suggest use of "signal(SIGCHLD, SIG_DFL)"

 - http://bugs.python.org/issue1068268 "subprocess is not EINTR-safe"

 - http://code.activestate.com/recipes/576582-openplus-open-pipes-urls-uniformly-with-popen-urlo/history/3/

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=17453
git-svn-id: http://svn.slicer.org/Slicer4/trunk@17453 3bd1e089-480b-0410-8dfb-8563597acbee