BUG: Ensure generic Python module tests pass when build as extension
After commit r19844 that ensure that python unittest will fail if it applies,
a problem associated with generic python module tests has been discovered.

The following error message was displayed:

   AttributeError: 'module' object has no attribute 'scriptedloadableextensiontemplate'


This was explained by the fact the path where the module was located
wasn't considered by the module factory manager.

To address that problem, a new command line option named

  --additional-module-paths

has been added.


The given list of path will added to the factory module manager.

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=19852
git-svn-id: http://svn.slicer.org/Slicer4/trunk@19852 3bd1e089-480b-0410-8dfb-8563597acbee