COMP: Update python-cmake-buildsystem anticipating python version update
Summary:
- Add support for building CPython 3.7.x, 3.8.x and 3.9.x
- cmake: Update minimum required version from 2.8.4 to 3.13.5
- 3.6.x: Add support for building asyncio module
- Deprecate SQLITE3_INCLUDE_PATH/SQLITE3_LIBRARY variables and prefer
  SQLite3_INCLUDE_DIR/SQLite3_LIBRARY.

List of python changes:

$ git shortlog dca8bee81..1feb43e4b --no-merges
Andras Lasso (1):
      Remove irrelevant comment

Dan Dees (3):
      cmake: Python 3.5.10 requires PY3_DLLNAME definition
      cmake: Display external libraries information
      3.7.x: Add USE_SYSTEM_FFI option

David Brooks (2):
      Add checksums for Python 3.5.6 to 3.5.10, 3.6.8 to 3.6.15. Set default to 3.6.15
      3.6.x: Add support for building asyncio module

Fernando Bordignon (6):
      circleci/linux: Expect tests to run in less than 360s
      circleci/linux: Install dependencies to build & test more extensions
      circleci/win: Update config to include windows build using VS2019
      3.7.x: Update approach for using release OpenSSL in debug CPython
      cmake: Fix list of requirements associated with _bsddb module
      3.6.x: Add support for building _testconsole module

James Butler (4):
      cmake: Add checksums for Python 3.8.7 to 3.8.12
      cmake: Add checksum for Python 3.9.10
      ci: Test latest patch release versions
      cmake: Update default version to 3.9.10

Jean-Christophe Fillion-Robin (49):
      PythonApplyPatches: Refactor logic applying patch to Python 2.7.11 and 2.7.12
      lzma: Fix Python 2.7 build excluding lzma extension introduced in Python 3.3
      ci/appveyor: Explicitly specify GENERATOR and PLATFORM
      ci/appveyor: Remove testing of 2.7.3 to 2.7.14
      ci/appveyor: Update 3.6.5 to 3.6.7, 2.7.14 to 2.7.15, Remove 3.5.5
      ci: Add CircleCI 2.0 configuration
      ci: Remove obsolete Circle 1.0 configuration
      circleci/linux: Update python 2.7.14 -> 2.7.15, 3.6.4 -> 3.6.7, remove 3.5.5
      cmake: Update add_python_extension to support NEVER_BUILTIN option
      cmake: Append "-static" to fix executable linking when WITH_STATIC_DEPENDENCIES is ON
      cmake: Fix undefined reference to gss_* symbols when WITH_STATIC_DEPENDENCIES is ON
      cmake: Update minimum required version from 2.8.4 to 3.13.5
      cmake: Remove unused custom CMake module for detecting CMake features
      cmake/Extensions: Simplify removing workaround specific to CMake < 2.8.8
      cmake: Fix undefined reference to gss_* symbols when libkrb5-dev package not installed
      PythonExtractVersionInfo: Support extracting version from patchlevel for alpha/beta/rc releases
      style: Simplify comparison using VERSION_GREATER_EQUAL if syntax
      audioop, _ctypes_test: Add missing libm dependency
      3.6.x: Update pyconfig.h.in and add missing configure checks
      ci: Remove obsolete travis configuration
      Add support for building Python 3.7.x
      Add checksums for 3.7.8 to 3.7.12, update CI and set default to 3.7.12
      PythonAutoDetectOSX: Fix query of SDK path converting SDK version into a two-component string
      ci: Add GitHub Actions config for building & testing on macOS
      cmake/config-unix/pyconfig.h.in: Consistently specify #cmakedefine
      cmake/config-unix/pyconfig.h.in: Ensure HAVE_GLIBC_MEMMOVE_BUG is defined
      circleci: Fix download of dashboard scripts using "git@" protocol
      cmake: Find SQLite3 using module provided by CMake
      cmake/config-unix/pyconfig.h.in: Consistently specify #cmakedefine
      Add support for building Python 3.8.x
      Add support for building Python 3.9.x
      cmake: Add tests at configure time based on files matching "test/test_*.py"
      3.6.x: Fix test_regrtest installing Tools/scripts/run_tests.py
      3.8.x: Fix test_fcntl on macOS ensuring _posixshmem module is built
      3.7.x: Fix incorrect PYTHONFRAMEWORK value returned by sysconfig.get_config_var
      ci/appveyor: Speed up CI removing Python 3.x jobs
      README: Update default version from 3.8.5 to 3.9.9
      cmake: Add checksums for Python 3.9.0 to 3.9.7
      PythonApplyPatches: Remove duplicated set of patches
      cmake/patches-win32: Remove obsolete patches related to VS2008 Express and VS2010
      cmake/patches-win32: Manage MinGW 2.7.x patches using PythonApplyPatches module
      README: Remove "Remarks" subsection and add new entry to FAQ
      README: Improve readability of overview section adding blank lines
      README: Update windows build instruction using VS2019 generator
      _testconsole: Fix link error when attempting to build extension as builtin on Linux
      cmake: Prevent some of 3.x built-in extensions from being registered twice
      datetime, time: Fix build conditionally including _time.c or timemodule.c
      cmake: Remove duplicated sources between libpython and extensions
      cmake: Mark relevant modules as ALWAYS_BUILTIN

Kai Hainke (1):
      PythonApplyPatches: Patch 2.7.[11|12] to support VS2015

Marcel Metz (1):
      cmake: Update extension BUILTIN to match CPython autoconf defaults

Minmin Gong (2):
      cmake: Skip CMP0045 on CMake >= 3.0.1
      cmake/extensions: Call set_target_properties only for enabled extensions

Walter Oggioni (1):
      Fix install specifying DESTDIR env. var

Co-authored-by: Fernando Bordignon <fernando@ltrace.com.br>