COMP: Update VTK to fix Windows build error related to .pyi files generation
This commit fixes a regression introduced in 396c8e5d0a (BUG: Fix crash in
vtkPolyData::BuildCells() and add .pyi generator) where the feature for
generation pyi files was inadvertently integrated.

The Windows build is fixed by removing vtkpythonmodules_pyi from the
default target (the "ALL" parameter was commented out) in the associated
custom target.

Until this is addressed, this should ensure the build succeeds.

Creating .pyi files for vtkpythonmodules
Traceback (most recent call last):
  File "C:\path\to\S-0-build\python-install\Lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\path\to\S-0-build\python-install\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\path\to\S-0-build\VTK-build\bin\Lib\site-packages\vtkmodules\generate_pyi.py", line 37, in <module>
    from vtkmodules.vtkCommonCore import vtkObject, vtkSOADataArrayTemplate
ImportError: DLL load failed while importing vtkCommonCore: The specified module could not be found.

List of VTK changes:

$ git shortlog 9b17870748..3ecff39979 --no-merges
Jean-Christophe Fillion-Robin (1):
      COMP: Fix Windows build removing vtkpythonmodules_pyi from the default target