BUG: Fix logging warning message when slicer.vtkPVScalarBarActor doesn't exist
This commit fixes a bug with logging a warning message. Because 'slicer.logging'
doesn't exist, the call to 'slicer.logging.warning()' failed with an error like:

      File "/path/to/Slicer-build/lib/Slicer-4.5/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 25, in __init__
	slicer.logging.warning("SliceAnnotations: Disable features relying on vtkPVScalarBarActor")
    AttributeError: 'module' object has no attribute 'logging'

Now the code calls 'logging.warning()'.

This warning was added in r24058. As described in that commit, the warning can
be triggered by starting Slicer with '--disable-builtin-loadable-modules'.

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25178
git-svn-id: http://svn.slicer.org/Slicer4/trunk@25178 3bd1e089-480b-0410-8dfb-8563597acbee