COMP: Use ITK OrientedBoundingBox Size Type instead Point Type
This commit fixes error like the following reported when building
against ITK configured with ITK_LEGACY_REMOVE set to ON:

```
C:\Dev\Slicer\Libs\vtkITK\vtkITKLabelShapeStatistics.cxx(325,85): error C2440: 'initializing': cannot convert from 'const slicer_itk::Vector<double,3>' to 'slicer_itk::Point<slicer_itk::ImageBase<3>::PointValueType,3>'
    C:\Dev\Slicer\Libs\vtkITK\vtkITKLabelShapeStatistics.cxx(325,85):
    Constructor for class 'slicer_itk::Point<slicer_itk::ImageBase<3>::PointValueType,3>' is declared 'explicit'
    C:\Dev\Slicer\Libs\vtkITK\vtkITKLabelShapeStatistics.cxx(325,85):
    the template instantiation context (the oldest one first) is
        C:\Dev\Slicer\Libs\vtkITK\vtkITKLabelShapeStatistics.cxx(405,7):
        see reference to function template instantiation 'void vtkITKLabelShapeStatisticsExecute<vtkITKLabelShapeStatistics::RequestData::VTK_TT>(vtkITKLabelShapeStatistics *,vtkImageData *,vtkTable *,vtkMatrix4x4 *,T *)' being compiled
        with
        [
            T=vtkITKLabelShapeStatistics::RequestData::VTK_TT
        ]
```