BUG: more robust sample data download
On some systems (e.g. windows 10) slicer temp files
are stored in storage that may get cleared from time to
time so that the entire temp directory structure
is cleared.

Previously, the Slicer code would try to create a directory
within the temp directory, but that would fail if the temp
directory itself was deleted (e.g. with the output below).

With this change, the mkdir is replaced by makedirs so that
the temp directory too is created.


<font color="red"><b>Failed to create cache folder /var/folders/md/_qs78z6s0rbfsth_95t95p800000gn/T/Slicer-pieper/RemoteIO</b></font>
<font color="red"><b>Cache folder /var/folders/md/_qs78z6s0rbfsth_95t95p800000gn/T/Slicer-pieper/RemoteIO is not writable</b></font>
<b>Requesting download</b> <i>MR-head.nrrd</i> from http://slicer.kitware.com/midas3/download/item/292308/MR-head.nrrd ...
<font color="red"><b>	Download failed: [Errno 2] No such file or directory: '/var/folders/md/_qs78z6s0rbfsth_95t95p800000gn/T/Slicer-pieper/RemoteIO/MR-head.nrrd'</b></font>
<b>Verifying checksum</b>
Traceback (most recent call last):
  File "/q5r/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SampleData.py", line 355, in <lambda>
    b.connect('clicked()', lambda s=source: logic.downloadFromSource(s))
  File "/q5r/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SampleData.py", line 609, in downloadFromSource
    filePath = self.downloadFileIntoCache(uri, fileName, checksum)
  File "/q5r/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SampleData.py", line 576, in downloadFileIntoCache
    return self.downloadFile(uri, destFolderPath, name, checksum)
  File "/q5r/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SampleData.py", line 819, in downloadFile
    current_digest = computeChecksum(algo, filePath)
  File "/q5r/Slicer-build/bin/Python/slicer/util.py", line 1701, in computeChecksum
    with open(filePath, 'rb') as content:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/md/_qs78z6s0rbfsth_95t95p800000gn/T/Slicer-pieper/RemoteIO/MR-head.nrrd'

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28473
git-svn-id: http://svn.slicer.org/Slicer4/trunk@28473 3bd1e089-480b-0410-8dfb-8563597acbee