BUG: Fix constructor of ScriptedLoadableModuleTest
This commit fixes a regression introduced in r24514 (ENH: allow self
tests to set a default message display) where the constructor
of the ScriptedLoadableModuleTest test case was specialized to set
a default value for messageDelay ivar.

Since the original constructor of a unittest.TestCase accept both
regular arguments and keyword arguments, constructor in derived class
have to use the form "*args, **kwargs".

This commit fixes the following tests:

  py_DTINotReproducibleIssue3977
  py_ColorsScalarBarSelfTest

Associated error was of the form:

//----------------
Traceback (most recent call last):
  File "/home/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/ColorsScalarBarSelfTest.py", line 120, in runTest
    self.test_ColorsScalarBarSelfTest1()
  File "/home/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/ColorsScalarBarSelfTest.py", line 124, in test_ColorsScalarBarSelfTest1
    self.delayDisplay("Starting the scalarbar test")
  File "/home/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/bin/Python/slicer/ScriptedLoadableModule.py", line 269, in delayDisplay
    slicer.util.delayDisplay(message, msec)
  File "/home/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/bin/Python/slicer/util.py", line 637, in delayDisplay
    qt.QTimer.singleShot(autoCloseMsec, messagePopup.close)
  File "/home/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/bin/Python/slicer/slicerqt.py", line 74, in _singleShot
    timer.start( msec )
ValueError: Could not find matching overload for given arguments:
('test_ColorsScalarBarSelfTest1',)
 The following slots are available:
start(int msec)
start()
//----------------

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24523
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24523 3bd1e089-480b-0410-8dfb-8563597acbee