COMP: Fix python-extension-manager-ssl-requirements build specifying "[crypto]"
This commit fixes a regression introduced in 7d58308e2 (COMP: Update
python packages to latest) by explicitly specifying "[crypto]".

It addresses the following error reported on macOS, Linux and Windows
when doing a clean build:

```
${SLICER_BUILD_DIR}/python-install/bin/PythonSlicer \
-m pip install \
  --require-hashes \
  -r ${SLICER_BUILD_DIR}/python-extension-manager-ssl-requirements-requirements.txt

[...]
Collecting pyjwt[crypto]>=2.4.0 (from PyGithub==1.59.0->-r <SLICER_BUILD_DIR>/python-extension-manager-ssl-requirements-requirements.txt (line 85))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    pyjwt[crypto]>=2.4.0 from https://files.pythonhosted.org/packages/2b/4f/e04a8067c7c96c364cef7ef73906504e2f40d690811c021e1a1901473a19/PyJWT-2.8.0-py3-none-any.whl (from PyGithub==1.59.0->-r /path/to/python-extension-manager-ssl-requirements-requirements.txt (line 85))
```