BUG: Fix error: AddMRMLDisplayableManagerEvent - eventId:16004 already added
Since some refactoring in related code, such errors appeared in the log:

ERROR: In C:\SAB\P\Slicer-0\Libs\MRML\DisplayableManager\vtkMRMLAbstractDisplayableManager.cxx, line 801
vtkMRMLAbstractDisplayableManager (000001F5B12AC5E0): AddMRMLDisplayableManagerEvent - eventId:16004 already added

The problem was that vtkMRMLAbstractDisplayableManager::AddMRMLDisplayableManagerEvent used GetSize() to get number of values in this->Internal->MRMLDisplayableNodeObservableEvents array. GetSize() returns the array capacity, not the actual number of values in the array. As elements are added to an array, capacity is increased exponentially (0, 1, 3, 7, ...) while actual size is increased linearly (0, 1, 2, ...), so uninitialized values were read from the array's buffer (which sometimes contained ID of already added events).

I've checked all other uses of GetSize() in the code based and fixed them (except errors in Charts classes, as they will be removed soon anyway).

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27663
git-svn-id: http://svn.slicer.org/Slicer4/trunk@27663 3bd1e089-480b-0410-8dfb-8563597acbee