COMP: Support building in RelWithDebInfo configuration on Windows
This commit fixes build errors when building in the RelWithDebInfo configuration
on Windows. Previously, projects that use OpenSSL_DIR would fail to find the
OpenSSL headers because only 'Debug' and 'Release' directories--not
'RelWithDebInfo'--are provided by the precompiled OpenSSL binaries.

An example error is:

    10>C:\S\R\Python-2.7.11\Modules\_hashopenssl.c(39): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory

Fixes https://issues.slicer.org/view.php?id=4058.

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25269
git-svn-id: http://svn.slicer.org/Slicer4/trunk@25269 3bd1e089-480b-0410-8dfb-8563597acbee