BUG: Fix "No LookupTable" error in qMRMLSliceWidget test
Full name of the test is: qMRMLSliceWidgetEventTranslatorPlayerTest1

The following error was reported:

//----------------------
ERROR: In /path/to/VTK/Imaging/vtkImageMapToColors.cxx, line 153
vtkImageMapToColors (0x268f190): RequestInformation: No LookupTable was set but number of components in input doesn't match OutputFormat, therefore input can't be passed through!

ERROR: In /path/to/VTK/Imaging/vtkImageExtractComponents.cxx, line 239
vtkImageExtractComponents (0x26947e0): Execute: Component 1 is not in input.

ERROR: In /path/to/VTK/Imaging/vtkImageExtractComponents.cxx, line 239
vtkImageExtractComponents (0x26947e0): Execute: Component 1 is not in input.
//----------------------

It is fixed by adding colorNodeRef attribute to VolumeDisplay element.

Also documented in the FAQ: https://www.slicer.org/w/index.php/Documentation/Nightly/Developers/FAQ#Developer_FAQ:_MRML

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=22654
git-svn-id: http://svn.slicer.org/Slicer4/trunk@22654 3bd1e089-480b-0410-8dfb-8563597acbee