COMP: Fix vtkMRMLModelStorageNode link error introduced by ITK update
This commit fixes the following link error introduced by r28458 (ENH: Update
ITK and use upstream repo):

  Libs/MRML/Core/CMakeFiles/MRMLCore.dir/vtkMRMLModelStorageNode.cxx.o:
  In function `itk::Mesh<double, 3u, itk::DefaultDynamicMeshTraits<double, 3u, 3u, double, float, double> >::PrintSelf(std::ostream&, itk::Indent) const':
  /path/to/Slicer-SuperBuild/ITK/Modules/Core/Mesh/include/itkMesh.hxx:57: undefined reference to `itk::operator<<(std::ostream&, itk::MeshClassCellsAllocationMethodType)'

Specific ITK commit introducing the regression is
InsightSoftwareConsortium/ITK@4fe3b5de7 (STYLE: Convert 'enum' to
'enum class' objects with print enum function )

See https://github.com/InsightSoftwareConsortium/ITK/commit/4fe3b5de74c6114e907747758746b3c4ea4406ff

Co-authored-by: Matt McCormick <matt.mccormick@kitware.com>
svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28462
git-svn-id: http://svn.slicer.org/Slicer4/trunk@28462 3bd1e089-480b-0410-8dfb-8563597acbee