COMP: fix mac/linux build errors in plot test
Need to pass raw pointer to set methods not vtkNew&

Errors of the form:

/home/pieper/slicer4/latest/Slicer/Modules/Loadable/Plots/Widgets/Testing/Cxx/qMRMLPlotPropertiesWidgetTest1.cxx: In function ‘int qMRMLPlotPropertiesWidgetTest1(int, char**)’:
/home/pieper/slicer4/latest/Slicer/Modules/Loadable/Plots/Widgets/Testing/Cxx/qMRMLPlotPropertiesWidgetTest1.cxx:97:38: error: no matching function for call to ‘vtkMRMLTableNode::SetAndObserveTable(vtkNew<vtkTable>&)’
   tableNode->SetAndObserveTable(table);
                                      ^
In file included from /home/pieper/slicer4/latest/Slicer/Modules/Loadable/Plots/Widgets/Testing/Cxx/qMRMLPlotPropertiesWidgetTest1.cxx:39:0:
/home/pieper/slicer4/latest/Slicer/Libs/MRML/Core/vtkMRMLTableNode.h:84:16: note: candidate: virtual void vtkMRMLTableNode::SetAndObserveTable(vtkTable*)
   virtual void SetAndObserveTable(vtkTable* table);

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26914
git-svn-id: http://svn.slicer.org/Slicer4/trunk@26914 3bd1e089-480b-0410-8dfb-8563597acbee