COMP: Fix qSlicerExtensionsInstallWidget build error adding  missing include
This commit fixes the following error reported when building against Qt > 5.10
and introduced by 98af6f222d (ENH: ExtensionsManager: Ensure theme of
extension catalog webpage is updated):

  Base/QTGUI/qSlicerExtensionsInstallWidget.cxx:161:39: error: invalid use of incomplete type ‘class QStyle’