BUG: Fix error due to default "None" node selection
The changes in this commit fix these errors:

```
Traceback (most recent call last):
  File "C:/D/S42/Modules/Scripted/LineProfile/LineProfile.py", line 142, in setup
    self.initializeParameterNode()
  File "C:/D/S42/Modules/Scripted/LineProfile/LineProfile.py", line 182, in initializeParameterNode
    self.setParameterNode(self.logic.getParameterNode())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/D/S42/Modules/Scripted/LineProfile/LineProfile.py", line 307, in getParameterNode
    return LineProfileParameterNode(super().getParameterNode())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\wrapper.py", line 138, in _initMethod
    parameter.write(self.parameterNode, parameter.default.value)
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\wrapper.py", line 41, in write
    self.serializer.write(parameterNode, self.name, value)
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\serializers.py", line 164, in write
    self.serializer.write(parameterNode, name, value)
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\serializers.py", line 1018, in write
    index, serializer = self._findBestSerializer(value)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\serializers.py", line 1014, in _findBestSerializer
    raise TypeError(f"Unable to write value '{value}' of type '{type(value)}'")
TypeError: Unable to write value 'None' of type '<class 'NoneType'>'
Traceback (most recent call last):
  File "C:/D/S42/Modules/Scripted/LineProfile/LineProfile.py", line 156, in enter
    self.initializeParameterNode()
  File "C:/D/S42/Modules/Scripted/LineProfile/LineProfile.py", line 182, in initializeParameterNode
    self.setParameterNode(self.logic.getParameterNode())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/D/S42/Modules/Scripted/LineProfile/LineProfile.py", line 307, in getParameterNode
    return LineProfileParameterNode(super().getParameterNode())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\wrapper.py", line 138, in _initMethod
    parameter.write(self.parameterNode, parameter.default.value)
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\wrapper.py", line 41, in write
    self.serializer.write(parameterNode, self.name, value)
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\serializers.py", line 164, in write
    self.serializer.write(parameterNode, name, value)
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\serializers.py", line 1018, in write
    index, serializer = self._findBestSerializer(value)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\S4R\Slicer-build\bin\Python\slicer\parameterNodeWrapper\serializers.py", line 1014, in _findBestSerializer
    raise TypeError(f"Unable to write value '{value}' of type '{type(value)}'")
TypeError: Unable to write value 'None' of type '<class 'NoneType'>'
```