BUG: Update SliceViewAnnotation to avoid error when restoring scene view
This commit avoid the test "py_RSNA2012ProstateDemo" to produce the errors
reported below.


Notes:

 (1) this commit does NOT fix the underlying issue. Indeed, after
restoring a scene view, no annotation are displayed.

 (2) after restoring the "" scene view, there is still error related to
     missing active camera:

       WorldToView: no active camera, cannot compute world to view, returning 0,0,0

 (3) after the test complete, when Slicer shutdown, the following warnings
     are still reported:

       Warning: In /path/to/VTKv6/Common/ExecutionModel/vtkAlgorithm.cxx, line 1421
       vtkOpenGLImageMapper (0x18a48f50): Attempt to get connection index 0 for input port 0, which has 0 connections.




The associated error messages were:

// ------------
Traceback (most recent call last):
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 622, in updateCornerAnnotations
    self.makeAnnotationText(caller)
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 808, in makeAnnotationText
    sliceViewName = sliceNode.GetLayoutName()
AttributeError: 'NoneType' object has no attribute 'GetLayoutName'
// ------------

and

// ------------
Restoring scene view Preoperative T2w MRI ...
test_RSNA2012ProstateDemo (RSNA2012ProstateDemo.RSNA2012ProstateDemoTest) ... Traceback (most recent call last):
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 605, in updateCornerAnnotations
    self.makeAnnotationText(caller)
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 808, in makeAnnotationText
    foregroundOpacity = sliceCompositeNode.GetForegroundOpacity()
AttributeError: 'NoneType' object has no attribute 'GetForegroundOpacity'
// ------------

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24127
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24127 3bd1e089-480b-0410-8dfb-8563597acbee