BUG: Fix regression in SubjectHierarchyCorePluginsSelfTest
This commit fixes a typo introduced in r24759 (STYLE: Update python
tests to use more specific asserts.):

  File "<string>", line 1, in <module>
  File "/path/to/Slicer-build/lib/Slicer-4.5/qt-scripted-modules/SubjectHierarchyCorePluginsSelfTest.py", line 186
    self.assertEqual( slicer.mrmlScene.GetNumberOfNodesByClass('vtkMRMLMarkupsFiducialStorageNode'), 2 )
       ^
SyntaxError: invalid syntax

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24767
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24767 3bd1e089-480b-0410-8dfb-8563597acbee