COMP: Error due to imporoper linkage specification
inline functions are required to be declared and defined
in the same scope.  The inline specifier changed the linkage
signature an prevented this from compiling.

Undefined symbols for architecture x86_64:
  "vtkMRMLSliceNode::GetNumberOfThreeDViewIDs() const", referenced from:
      PyvtkMRMLSliceNode_GetNumberOfThreeDViewIDs(_object*, _object*) in vtkMRMLSliceNodePython.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23020
git-svn-id: http://svn.slicer.org/Slicer4/trunk@23020 3bd1e089-480b-0410-8dfb-8563597acbee