BUG: Fix tracebacks settings attributes for ctkDICOMRetrieve
Introduced by https://github.com/commontk/CTK/commit/037fca7425a9b96a53be5776b263d42dc7b1eaa6 integrated into Slicer by way of https://github.com/Slicer/Slicer/commit/ca187f59744b827b75bc7899f54bf9289d3485d9.

Traceback (most recent call last):
  File "C:/S5R/Slicer-build/lib/Slicer-5.9/qt-scripted-modules/JRC2013Vis.py", line 237, in test_Part1DICOM
    dicomRetrieve.setKeepAssociationOpen(True)
AttributeError: ctkDICOMRetrieve has no attribute named 'setKeepAssociationOpen'