COMP: Revert back to VTK 6.1. See #3741
It turns out that updating the version of XCode  used on the factory
(running Snow Leopard) from 3.2.6 to 4.2 avoids to get the rather
obnoxious errors of the form:

// ---------------------
[ 53%] Built target vtkSlicerAtlasCreatorModuleLogic
Linking CXX shared library ../../../../lib/Slicer-4.3/qt-loadable-modules/libvtkSlicerAtlasCreatorModuleLogicPythonD.dylib
ld: warning: duplicate dylib /Users/kitware/Dashboards/Experimental/Slicer4-SB/python-install/lib/libpython2.7.dylib
ld: two level namespace mach-o files can link with at most 253 dylibs, this link would use 257 dylibs
collect2: ld returned 1 exit status
// ---------------------

This has been confirmed doing

(1) a clean build of Slicer r23525 using:
 Slicer/VTK@169b37b
 CMake 2.8.12

(2) a clean build of CarreraSlice against the Slicer build tree
obtain in (1) also using CMake 2.8.12

More particularly, this commit reverts r23512, r23513, r23514 and r23515
The code checking for the version of CMake and enabling the option
VTK_ENABLE_KITS only available with kitware/VTK@a609ca has been removed.

XCode before:

 * Xcode: 3.2.6 - uildVersion: 10M2518
 * gcc-4.0: i686-apple-darwin10-gcc-4.0.1 (GCC) 4.0.1 (Apple Inc. build 5494)
 * gcc-4.2: i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666) (dot 3)
 * llvm-gcc: i686-apple-darwin10-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.6)
 * clang: Apple clang version 1.7 (tags/Apple/clang-77) (based on LLVM 2.9svn

XCode after:

 * Xcode: 4.2 - Build version 4C199
 * gcc-4.0: i686-apple-darwin10-gcc-4.0.1 (GCC) 4.0.1 (Apple Inc. build 5494)
 * gcc-4.2: i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666) (dot 3)
 * llvm-gcc: i686-apple-darwin10-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.1.00)
 * clang: Apple clang version 3.0 (tags/Apple/clang-211.10.1) (based on LLVM 3.0svn)

The XCode configuration details has been obtained using the following
one-liner adapted from the one available on XcodeVersionInfo macports
page [1]:

// --------------------
echo -en " * Xcode: $(/usr/bin/xcodebuild -version |head -n1) - $(/usr/bin/xcodebuild -version |tail -1)\n\
$(test -x /usr/bin/gcc-3.3\
&& echo " * gcc-3.3: $(/usr/bin/gcc-3.3 --version 2>/dev/null |head -1)\n")\
$(test -x /usr/bin/gcc-4.0\
&& echo " * gcc-4.0: $(/usr/bin/gcc-4.0 --version 2>/dev/null |head -1)\n")\
$(test -x /usr/bin/gcc-4.2\
&& echo " * gcc-4.2: $(/usr/bin/gcc-4.2 --version 2>/dev/null |head -1)\n")\
$((test -x /usr/bin/llvm-gcc-4.2 || test -x /Developer/usr/bin/llvm-gcc-4.2)\
&& echo " * llvm-gcc: $((/usr/bin/llvm-gcc --version 2>/dev/null || /Developer/usr/bin/llvm-gcc --version 2>/dev/null) |head -1)\n")\
$((test -x /usr/bin/clang || test -x /Developer/usr/bin/clang)\
&& echo " * clang: $((test -x /usr/bin/clang\
&& /usr/bin/clang --version 2>&1 || /Developer/usr/bin/clang --version 2>&1) |head -1)\n")"
// --------------------

Note also that running this on-liner using the freshly installed version
of XCode return the following message:

** INTERNAL ERROR: Uncaught exception **
Exception: *** -[NSConcreteFileHandle writeData:]: Broken pipe


Finally, for future reference, the package allowing to install xcode is
named "xcode_4.2_for_snow_leopard.dmg" and the associated
MD5 is "428b006e1c12eaa644a442a598c6f13f". It has been installed using
the default option in the "/Developer" folder.

[1] https://trac.macports.org/wiki/XcodeVersionInfo

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23528
git-svn-id: http://svn.slicer.org/Slicer4/trunk@23528 3bd1e089-480b-0410-8dfb-8563597acbee