BUG: Add missing import to ScriptedLoadableModule
This commit fixes the following error when using takeScreenshot from a
ScriptedLoadableModuleLogic subclass:
```
  File "path\to\slicer\Python\slicer\ScriptedLoadableModule.py", line
  344, in takeScreenshot
      imageData = vtk.vtkImageData()
      NameError: name 'vtk' is not defined
```