COMP: Fix CERTIFICATE_VERIFY_FAILED build error when SimpleITK is enabled.
This commit is a follow-up of:
  * r24652 (BUG: ExtensionsWizard: Fix CERTIFICATE_VERIFY_FAILED publishing error)
  * r24662 (BUG: Fix CERTIFICATE_VERIFY_FAILED error using "urllib2.urlopen()" on MacOSX)

It updates the SlicerPython launcher settings configuration script so that
it copies the certificate file (Slicer.crt) where it is expected.

It basically fixes the error reported below:

8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---
Installed /path/to/Slicer/python-install/lib/python2.7/site-packages/SimpleITK-0.10.0.dev127-py2.7-macosx-10.11-x86_64.egg
Processing dependencies for SimpleITK==0.10.0.dev127
Searching for SimpleITK==0.10.0.dev127

Reading https://pypi.python.org/simple/SimpleITK/
Scanning index of all packages (this may take a while)

Reading https://pypi.python.org/simple/
warning: manifest_maker: standard file 'setup.py' not found

zip_safe flag not set; analyzing archive contents...
SimpleITK.SimpleITK: module references __file__

Download error on https://pypi.python.org/simple/SimpleITK/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'SimpleITK' (maybe misspelled?)

Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for SimpleITK==0.10.0.dev127
error: Could not find suitable distribution for Requirement.parse('SimpleITK==0.10.0.dev127')

CMake Error at /path/to/Slicer/CMake/ExternalProjectForNonCMakeProject.cmake:76 (message):
  SimpleITK: Error in install step.  See
  /path/to/Slicer/SimpleITK_install_step_output.txt and
  /path/to/Slicer/SimpleITK_install_step_error.txt
Call Stack (most recent call first):
  /path/to/Slicer/SimpleITK_install_step.cmake:3 (ExternalProject_Execute)
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-install] Error 1
[...]
8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---

Reported-by: Hans Johnson <hans-johnson@uiowa.edu>

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24719
git-svn-id: http://svn.slicer.org/Slicer4/trunk@24719 3bd1e089-480b-0410-8dfb-8563597acbee