COMP: Fix build error occurring with gcc >= 4.8
This commit fixes the following build error introduced by commit r23148:

/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx: In function ‘bool SetVTKBSplineFromITK(vtkObject*, vtkOrientedBSplineTransform*, itk::TransformBaseTemplate<double>::Pointer, itk::TransformBaseTemplate<double>::Pointer)’:
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:394:14: error: expected nested-name-specifier before ‘BulkTransformType’
     typename BulkTransformType* bulkItkAffine = dynamic_cast<BulkTransformType*> (bulkTransformItk.GetPointer());
              ^
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:394:14: error: expected ‘(’ before ‘BulkTransformType’
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:394:14: error: expected ‘;’ before ‘BulkTransformType’
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:395:14: error: expected nested-name-specifier before ‘IdentityBulkTransformType’
     typename IdentityBulkTransformType* bulkItkIdentity = dynamic_cast<IdentityBulkTransformType*> (bulkTransformItk.GetPointer());
              ^
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:395:14: error: expected ‘(’ before ‘IdentityBulkTransformType’
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:395:14: error: expected ‘;’ before ‘IdentityBulkTransformType’
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:398:9: error: ‘bulkItkAffine’ was not declared in this scope
     if (bulkItkAffine)
         ^
/path/to/Slicer/Libs/MRML/Core/vtkMRMLTransformStorageNode.cxx:414:14: error: ‘bulkItkIdentity’ was not declared in this scope
     else if (bulkItkIdentity)

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23153
git-svn-id: http://svn.slicer.org/Slicer4/trunk@23153 3bd1e089-480b-0410-8dfb-8563597acbee