BUG: Fix ExtensionWizard error message reporting when drag-and-dropping script
This commit addresses a regression introduced in 34651fbbb (BUG: Fix error
message when drag-and-dropping nodes).

The problem stemmed from the "errorDisplay()" function, which expects the
argument to be provided as "text, windowTitle=None, parent=None, standardButtons=None, **kwargs".

Specifying "parent" as a keyword argument is then required to avoid the
following error:

Traceback (most recent call last):
  File "/path/to/Slicer-Release/Slicer-build/lib/Slicer-5.5/qt-scripted-modules/ExtensionWizard.py", line 518, in dropEvent
    ExtensionWizardWidget.loadModules(modules=self.foundModules)
  File "/path/to/Slicer-Release/Slicer-build/lib/Slicer-5.5/qt-scripted-modules/ExtensionWizard.py", line 407, in loadModules
    slicer.util.errorDisplay(text, parent, windowTitle="Error loading module(s)",
TypeError: errorDisplay() got multiple values for argument 'windowTitle'