COMP: Fix installation of SimpleITK
This commit fixes a regression introduced in 127dfbad28 (COMP: Update
SimpleITK from v2.0rc3 to v2.0.0 (#5212)) and ensures that ITK libraries
are in the PATH when running the command:

  cd /path/to/SimpleITK-build/SimpleITK-build/Wrapping/Python
  python setup.py install

It addresses the following error:

  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/work/Preview/Slicer-0-build/SimpleITK-build/SimpleITK-build/Wrapping/Python/SimpleITK/__init__.py", line 18, in <module>
      from SimpleITK.SimpleITK import *
    File "/work/Preview/Slicer-0-build/SimpleITK-build/SimpleITK-build/Wrapping/Python/SimpleITK/SimpleITK.py", line 13, in <module>
      from . import _SimpleITK
  ImportError: libITKIOBruker-5.1.so.1: cannot open shared object file: No such file or directory