BUG: Update EditBox.py to use setExclusive method
Use method to enable the group exclusion checking property.
Direct assignment of this property results in the message:
      AttributeError: 'exclusive' does not exist on QActionGroup and creating new attributes on C++ objects is not allowed
and the EditBox will not open.