ENH: Log error details if slicer.util file read/write operation fails
(cherry picked from commit 43a34e22c)

Example:

>>> loadModel(r'c:\Users\andra\OneDrive\Projects\SlicerTesting2022\20220622-EmptyPolyData\slicer5-fail-T_Sup-O_right.vtp')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\D\S4D\Slicer-build\bin\Python\slicer\util.py", line 820, in loadModel
    return loadNodeFromFile(filename, 'ModelFile', {}, returnNode)
  File "C:\D\S4D\Slicer-build\bin\Python\slicer\util.py", line 685, in loadNodeFromFile
    raise RuntimeError(errorMessage)
RuntimeError: Failed to load node from file: c:\Users\andra\OneDrive\Projects\SlicerTesting2022\20220622-EmptyPolyData\slicer5-fail-T_Sup-O_right.vtp
- Error: Loading c:\Users\andra\OneDrive\Projects\SlicerTesting2022\20220622-EmptyPolyData\slicer5-fail-T_Sup-O_right.vtp - ERROR: In C:\D\S4D\VTK\IO\XML\vtkXMLUnstructuredDataReader.cxx, line 393
vtkXMLPolyDataReader (00000254994D0CC0): No Points element available in first piece found in file. Reading file may fail.
- Error: Loading c:\Users\andra\OneDrive\Projects\SlicerTesting2022\20220622-EmptyPolyData\slicer5-fail-T_Sup-O_right.vtp - Failed to read node slicer5-fail-T_Sup-O_right (vtkMRMLModelNode4) from filename='c:\Users\andra\OneDrive\Projects\SlicerTesting2022\20220622-EmptyPolyData\slicer5-fail-T_Sup-O_right.vtp'

see #6447