BUG: slicer.util: Add missing import to pythonShell function
This commit fixes the following error:

```
>>> slicer.util.pythonShell()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path/to/Slicer-build/Slicer-build/bin/Python/slicer/util.py", line 147, in pythonShell
    console = slicer.app.pythonConsole()
NameError: global name 'slicer' is not defined
```

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26278
git-svn-id: http://svn.slicer.org/Slicer4/trunk@26278 3bd1e089-480b-0410-8dfb-8563597acbee