BUG: workaround change in vtk python behavior
With recen builds, making this call:

  slicer.mrmlScene.GetNodeByID(None)
 
results in this error:

  Traceback (most recent call last):
    File "<console>", line 1, in <module>
  TypeError: argument 1: string is required

in older slicer builds this was not the case (None was returned).  
The only related changes seem to be the removal of 
//BTX, //ETX but I don't see why this would have an impact.




svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=18511
git-svn-id: http://svn.slicer.org/Slicer4/trunk@18511 3bd1e089-480b-0410-8dfb-8563597acbee