COMP: qSlicerApplicationHelper: Fix Qt4 build error adding missing includes
This commit fixes the following build error:

/path/to/Slicer/Base/QTApp/qSlicerApplicationHelper.cxx:268:3: error: ‘vtkNew’ was not declared in this scope
   vtkNew<vtkSystemInformation> systemInfo;
   ^

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27453
git-svn-id: http://svn.slicer.org/Slicer4/trunk@27453 3bd1e089-480b-0410-8dfb-8563597acbee