BUG: Fix import of urllib MacOsx by updating CMake'ified python
Thanks to Steve Pieper for reporting the issue.

Following Slicer commit r21863 and commit r21867, CMake'ified python is
used to build Slicer. This commit update the python project so that the
python extension _scproxy is also built.

// ---------
The error being fixed was:

File "/Users/pieper/slicer4/latest/Slicer-superbuild/Slicer-build/lib/Slicer-4.2/qt-scripted-modules/SampleData.py", line 192, in downloadFile
  import urllib
File "/Users/pieper/slicer4/latest/Slicer-superbuild/python-install/lib/python2.7/urllib.py", line 1379, in <module>
  from _scproxy import _get_proxy_settings, _get_proxies
ImportError: No module named _scproxy
// ---------

The associated commit in CMake'ified python is:
https://github.com/davidsansome/python-cmake-buildsystem/commit/a813b59647eb40b8c6a3411eee83268ae98c9452

See https://issues.slicer.org/view.php?id=3052
Fixes #3052

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=21869
git-svn-id: http://svn.slicer.org/Slicer4/trunk@21869 3bd1e089-480b-0410-8dfb-8563597acbee