COMP: Convert to vtkMTimeType for modified times to fix compile errors
https://gitlab.kitware.com/vtk/vtk/merge_requests/1790 ("ENH: Introduce
vtkMTimeType") adds vtkMTimeType as a typedef for vtkObject modified times,
replacing unsigned long. This commit updates Slicer to use the new type. This
fixes compile errors like:

    c:\path\to\slicer\libs\vtkteem\vtkDiffusionTensorGlyph.h(192): error C2555: 'vtkDiffusionTensorGlyph::GetMTime': overriding virtual function return type differs and is not covariant from 'vtkObject::GetMTime'

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25333
git-svn-id: http://svn.slicer.org/Slicer4/trunk@25333 3bd1e089-480b-0410-8dfb-8563597acbee