COMP: Fix setting of Slicer_SUPERBUILD_DIR for Slicer Custom application
This commit updates the build system so that it:
* ensures that python files are packaged
* an error is reported if "PYTHON_DIR" variable is not set in SlicerBlockInstallPython

Symptom leading to this fix was the following error reported when
starting the application:

  ImportError: No module named site

Co-authored-by: Dženan Zukić <dzenan.zukic@kitware.com>
svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26774
git-svn-id: http://svn.slicer.org/Slicer4/branches/Slicer-4-8@26774 3bd1e089-480b-0410-8dfb-8563597acbee