BUG: Fix IndentationError in DICOMPlugin.py
This commit fixes regression introduced in r23939 (ENH: Transfer
referencedInstanceUIDs to the MRML attribute).

Runtime error:

// -------------
Fail to instantiate module "DICOMSlicerDataBundlePlugin"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/MultiVolumeImporterPlugin.py", line 4, in <module>
    from DICOMLib import DICOMPlugin
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DICOMLib/__init__.py", line 5, in <module>
    from DICOMPlugin import *
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DICOMLib/DICOMPlugin.py", line 208
    referencedInstanceUIDs += instanceUID + " "
                         ^
IndentationError: expected an indented bloc
// -------------

svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23945
git-svn-id: http://svn.slicer.org/Slicer4/trunk@23945 3bd1e089-480b-0410-8dfb-8563597acbee