COMP: Fix build error on Windows
Errors like this occurred when compiling vtkMRMLMeasurement on Windows (using VTK8):
C:\d\Slicer\Libs\MRML\Core\vtkMRMLMeasurement.h(158,3): error C2666: 'vtkOStreamWrapper::operator <<': 5 overloads have similar conversions [C:\d\S4D\Slicer-build\Libs\MRML\Core\MRMLCore.vcxproj] [C:\d\S4D\Slicer.vcxproj]

They were due to using vtkGetObjectMacro for vtkSmartPointer objects.