COMP: Fix Windows build errors by explicitly including `Windows.h`
Explicitly include `Windows.h` in `Base/QTCLI/vtkSlicerCLIModuleLogic.cxx` and
`Base/QTGUI/qSlicerApplication.cxx` to ensure the availability of Windows-specific
symbols `MEMORYSTATUSEX` and functions `GetCurrentProcessId()` and `GlobalMemoryStatusEx()`.

This fixes a regression introduced in commit 975fa530e49 ("COMP: Remove direct dependency
on ITK from vtkSlicerApplicationLogic", 2025-01-28), which removed the `itkThreadSupport.h`
include from `vtkSlicerApplicationLogic.h`. Since `itkThreadSupport.h` indirectly included
`Windows.h`, its removal caused missing Windows definitions in `qSlicerApplication.cxx` and
`vtkSlicerCLIModuleLogic.cxx`, leading to the following errors:

- `Base/QTGUI/qSlicerApplication.cxx(1237,3): error C2065: 'MEMORYSTATUSEX': undeclared identifier`
- `Base/QTCLI/vtkSlicerCLIModuleLogic.cxx(469,16): error C3861: 'GetCurrentProcessId': identifier not found`

Note that although `MEMORYSTATUSEX` and `GlobalMemoryStatusEx()` are defined in `sysinfoapi.h`,
including only `sysinfoapi.h` results in the following error:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\winnt.h(169,1):
error C1189: #error: "No Target Architecture"
```

Including `Windows.h` ensures all required dependencies are correctly included.

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>